### ISSUE TITLE
Navigation - implement basic nav between two pages

### ISSUE THREAD

**Issue by RcDevRIL** [RcDevRIL/cesi_covid_19_tracker#8]
# TODO:
* [x] Implement two pages
* [x] Implement a Drawer or some links on the AppBar
* [x] Structure the app files to keep it clean

**Comment by Reyden7** [comment]
test

**Comment by RcDevRIL** [comment]
Encore un commit pour finir la structuration du projet puis PR pour merge^^ @FerreiraJames quand je l'aurais fait tu connais la marche a suivre? :p Files changed>Review changes>Approve
